### PR TITLE
Monte Carlo 1: minor changes

### PR DESCRIPTION
**Pull request by davidreber**
Minor changes to avoid misunderstanding in problems, as requested by @jmorrise.

### CODE REVIEW

**Comment by davidreber** [comment]
@shanemcq18 Do you know what the failure is? All I did was make wording changes to the .tex file after I newly pulled and created a new branch this morning, so it should run the same as it did. 

However, it says it's missing a `iftex.sty` file.

**Comment by shanemcq18** [comment]
I'm crawling through it right now to find the problem. The same thing is happening on my pull request. It's got to be something that I did––I'm thinking it's a latex package that I included that isn't supported or something.

**Comment by shanemcq18** [comment]
The best thing I can find from Travis is [here](https://docs.travis-ci.com/user/common-build-problems/#My-tests-broke-but-were-working-yesterday). It looks like the LaTeX that we download and use in the Travis CI was recently changed so that the file `/usr/local/texlive/2014/texmf-dist/tex/generic/iftex/iftex.sty` isn't included.

This might be bad news.

**Comment by shanemcq18** [comment]
Fixed Travis. Closing this Pull Request in favor of #1258.

**Pull request closed without merging**
