### PR TITLE
Rainbows

### PR DESCRIPTION
**Pull request by jmorrise**
See #1229. Edits to the Complex 1 lab.

### CODE REVIEW

**Comment by jmorrise** [comment]
The Travis build failed because the iPython notebook was too large. Where do we put notebooks?

**Comment by shanemcq18** [comment]
Keep the notebook. To shrink it, restart the kernel and clear all outputs. The resulting file will have all the code, but it won't include memory-expensive pictures.

**Comment by jmorrise** [comment]
Thanks! Did that

**Comment by jmorrise** [comment]
@shanemcq18 @Mylancook What should I do with old files that were part of a completely different version of the lab?

**Comment by shanemcq18** [comment]
Nuke them. Use `git rm` to specify which files to delete. If we need them later we can get them from the git history.

**Pull request merged**
