### PR TITLE
Rewrote the value function iteration lab.

### PR DESCRIPTION
**Pull request by jaredawebb**
This is the new value function iteration lab.  I have rough draft material to expand on this, but I would like to run this by someone else and get feedback on length and understandability first.

### CODE REVIEW

**Comment by shanemcq18** [comment]
You need to force add diff_policies.pdf with `git add -f diff_policies`.

**Comment by jaredawebb** [comment]
Sorry, forgot to do that.  I'll add it and redo the request.

**Comment by jaredawebb** [comment]
Or do I need to redo it? It looks like the new commit just got put into the
current request?

I'm sorry I do not understand git.

**Comment by shanemcq18** [comment]
New commits go straight to this pull request so you shouldn't have to redo a pull request, but I'm not sure why the test didn't pass the second time. Here's the error on the build:
```[latex]
! Package pdftex.def Error: File `diff_policies.pdf' not found.
l.94 ...phics[width=\textwidth]{diff_policies.pdf}
```

I think the problem is that the graphic is located at:
`Labs/Vol2b/ValueFunctionIteration/diff_policies.pdf`

Notice that `Vol2b` has a lower-case `b`. The other files are in the folder `Vol2B` with an upper-case `B`. Maybe double check your file system and make sure that the figure is in the right place?

**Pull request merged**
